# build work flow
name: Java CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{github.sha}}
jobs:
  clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Clone-down
      uses: actions/checkout@v3
    - name: Upload repo
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .
  build:
    needs: clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: Build application
      run:  chmod +x ci/build-app.sh && ci/build-app.sh
    - name: Test
      run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
    - name: Upload repo
      uses: actions/upload-artifact@v3
      with:
        name: code2
        path: .
  docker-image:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download lib
      uses: actions/download-artifact@v2
      with:
        name: code2
        path: .
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.docker_username }}
        password: ${{ env.docker_password }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: $docker_username/micronaut-app:1.0-${GIT_COMMIT::8} 