name: Storing Artefacts
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down
        uses: actions/checkout@v3       
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: Clone down
        uses: actions/checkout@v3     
      - name: Build application
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload Repo as artifact
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .
    
